// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDJLIiFkGPSqUQjhsPZQhROEdMVSpg4314',
    appId: '1:22012254675:web:9cc02e00a061294ff17726',
    messagingSenderId: '22012254675',
    projectId: 'my-custom-routes',
    authDomain: 'my-custom-routes.firebaseapp.com',
    storageBucket: 'my-custom-routes.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBAyg-MlJDSfhg36ggVm6m6zvX3FRYuuoY',
    appId: '1:22012254675:android:c26dcb590bcb746bf17726',
    messagingSenderId: '22012254675',
    projectId: 'my-custom-routes',
    storageBucket: 'my-custom-routes.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDF-M4gRN2FPRNDS28U0vmYekqgu2vWhj4',
    appId: '1:22012254675:ios:2e65eeabf07d7691f17726',
    messagingSenderId: '22012254675',
    projectId: 'my-custom-routes',
    storageBucket: 'my-custom-routes.appspot.com',
    iosClientId: '22012254675-3fveh4h7hcdbluen8t3jfgjlkgc1b3l1.apps.googleusercontent.com',
    iosBundleId: 'com.example.customRoutes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDF-M4gRN2FPRNDS28U0vmYekqgu2vWhj4',
    appId: '1:22012254675:ios:2e65eeabf07d7691f17726',
    messagingSenderId: '22012254675',
    projectId: 'my-custom-routes',
    storageBucket: 'my-custom-routes.appspot.com',
    iosClientId: '22012254675-3fveh4h7hcdbluen8t3jfgjlkgc1b3l1.apps.googleusercontent.com',
    iosBundleId: 'com.example.customRoutes',
  );
}
